baskets/urls.py
from django.urls import path

from baskets.views import basket_add, basket_remove, basket_edit

app_name = 'baskets'
urlpatterns = [

    path('add/<int:product_id>', basket_add, name='basket'),
    path('remove/<int:product_id>', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit')
]

geekshop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from products.views import ProductsIndex

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index, name='index'),
    path('', ProductsIndex.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('feedbacks/', include('feedbacks.urls', namespace='feedbacks')),

]

if settings.DEBUG:
    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [re_path('^__debug__/', include(debug_toolbar.urls))]
    # urlpatterns +=[path('^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from .views import OrderCreate, OrderList, OrderDetail, OrderDelete, OrderUpdate, order_forming_complete

app_name = 'ordersapp'
urlpatterns = [

    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),

]

users/urls.py
from django.urls import path
from .views import LoginLoginView, Logout, RegisterListView, ProfileFormView

app_name = 'users'
urlpatterns = [

    path('login/', LoginLoginView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),

    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify')

]

baskets/models.py
from django.db import models
from django.utils.functional import cached_property

from users.models import User
from products.models import Product


# Create your models here.


class BasketQueryset(models.QuerySet):

    def delete(self, *args, **kwargs):
        for item in self:
            item.product.quantity +=item.quantity
            item.product.save()
        super(BasketQueryset, self).delete()


class Basket(models.Model):
    objects = BasketQueryset.as_manager()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    # @staticmethod
    # def total_sum(self):
    #     baskets=Basket.objects.filter(user=self.user)
    #     return sum(basket.sum() for basket in baskets)
    #
    # @staticmethod
    # def total_quantity(self):
    #     baskets=Basket.objects.filter(self.user)
    #     return sum(basket.quantity for basket in baskets)

    def total_quantity(self):
        # baskets = Basket.objects.filter(user=self.user)
        baskets = self.get_cache_item
        return sum(basket.quantity for basket in baskets)

    def total_sum(self):
        # baskets = Basket.objects.filter(user=self.user)
        baskets = self.get_cache_item
        return sum(basket.sum() for basket in baskets)

    # def total_sum_qnty(request):
    #     total_sum = 0
    #     total_qnty = 0
    #     for basket in Basket.objects.filter(user=request.user):
    #         total_sum += basket.sum()
    #         total_qnty += basket.quantity
    #     return total_sum, total_qnty

    def delete(self, using=None, keep_parents=False):
        self.product.quantity += self.quantity
        self.product.save()
        super(Basket, self).delete()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.pk:
            self.product.quantity -= self.quantity - self.get_item(int(self.pk))
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super(Basket, self).save()

    @staticmethod
    def get_item(pk):
        return Basket.objects.get(pk=pk).quantity

    @cached_property
    def get_cache_item(self):
        return self.user.basket.select_related()

baskets/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import JsonResponse
from django.shortcuts import render

from django.shortcuts import HttpResponseRedirect
from django.template.loader import render_to_string

from products.models import Product
from baskets.models import Basket
# Create your views here.

@login_required
def basket_add(request, product_id):


    user_select = request.user
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=user_select, product=product).select_related('user', 'product')
    if not baskets.exists():
        Basket.objects.create(user=user_select, product=product, quantity=1)

    else:
        basket = baskets.first()
        # basket.quantity+=1
        basket.quantity = F('quantity') + 1
        basket.save()


    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_remove(request, product_id):
    Basket.objects.get(id=product_id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_edit(request, id, quantity):
    pass
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()

        baskets = Basket.objects.filter(user = request.user).select_related('user', 'product')
        context = {
            'baskets': baskets
        }
        result = render_to_string('baskets/baskets.html', context)
        return JsonResponse({'result': result})

baskets/templates/baskets/baskets.html
{% load method %}

<div class="basket_list">

    {% if not basket %}

        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
{#            Корзина <span class="badge badge-secondary badge-pill">{{ variable|total_quantity:user }}</span>#}

            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>

        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }}</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                {#                <h4 class="float-right">{{ variable|total_sum:user }}</h4>#}
                <h4 class="float-right">{{ baskets.0.total_sum }}</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right" > <a href={% url 'orders:create' %}> Оформить </a></button>
    {% else %}
        <h5>Корзина пуста</h5>
    {% endif %}

</div>