baskets/urls.py
from django.urls import path

from baskets.views import basket_add, basket_remove, basket_edit

app_name = 'baskets'
urlpatterns = [

    path('add/<int:product_id>', basket_add, name='basket'),
    path('remove/<int:product_id>', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit')
]

geekshop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from products.views import ProductsIndex

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index, name='index'),
    path('', ProductsIndex.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('feedbacks/', include('feedbacks.urls', namespace='feedbacks')),

]

if settings.DEBUG:
    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [re_path('^__debug__/', include(debug_toolbar.urls))]
    # urlpatterns +=[path('^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from .views import OrderCreate, OrderList, OrderDetail, OrderDelete, OrderUpdate, order_forming_complete

app_name = 'ordersapp'
urlpatterns = [

    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),

]

products/urls.py
from django.urls import path


from .views import ProductsListView, ProductDetailView

app_name = 'products'
urlpatterns = [

    path('', ProductsListView.as_view(), name='index'),
    # path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    # path('page/<int:page_id>/', products, name='page'),
    path('page/<int:page_id>/', ProductsListView.as_view(), name='page'),
    path('category/<int:category_id>/page/<int:page_id>/', ProductsListView.as_view(), name='category_page'),
    path('price/<int:pk>/', ProductsListView.get_price, name='price'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),

]

users/urls.py
from django.urls import path
from .views import LoginLoginView, Logout, RegisterListView, ProfileFormView

app_name = 'users'
urlpatterns = [

    path('login/', LoginLoginView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),

    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify')

]

products/models.py
from django.db import models

# Create your models here.



class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    discount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    final_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_product_price(self):
        return self.price

products/views.py
import django.shortcuts
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView

from feedbacks.models import Feedback
from products.models import Product, ProductCategory
from geekshop.settings import MEDIA_URL
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.cache import cache
from django.shortcuts import get_object_or_404


# Create your views here.

class ProductsListView(ListView):
    model = Product
    title = 'Каталог'
    template_name = 'products/products.html'
    # Выводим по три объекта на страницу
    paginate_by = 3

    @staticmethod
    def get_product(pk):
        if settings.LOW_CACHE:
            key = f'product{pk}'
            product = cache.get(key)
            if product is None:
                product = Product.objects.get(pk=pk)
                cache.set(key, product)
            return product
        else:
            return Product.objects.get(pk=pk)

    @staticmethod
    def get_links_category():
        if settings.LOW_CACHE:
            key = 'links_category'
            links_category = cache.get(key)
            if links_category is None:
                links_category = ProductCategory.objects.all()
                cache.set(key, links_category)
            return links_category
        else:
            return ProductCategory.objects.all()

    @staticmethod
    def get_links_product():
        if settings.LOW_CACHE:
            key = 'links_product'
            links_product = cache.get(key)
            if links_product is None:
                links_product = Product.objects.all()
                cache.set(key, links_product)
            return links_product
        else:
            return Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['products'] = self.get_links_product()
        context['categories'] = self.get_links_category()
        context['page_quantity'] = range(1, len(self.object_list) // self.paginate_by + 2)
        context['page_max'] = len(self.object_list) // self.paginate_by + 1
        # флаг для првоерки отфильтрованы ли продукты по категории
        context['is_categorised'] = True if self.kwargs.get('category_id') else False
        if self.kwargs.get('page_id'):
            context['page_obj'].number = self.kwargs.get('page_id')
            context['page_obj'].object_list = self.object_list[context[
                                                                   'page_obj'].number * self.paginate_by - self.paginate_by:self.paginate_by *
                                                                                                                            context[
                                                                                                                                'page_obj'].number]
        # как оказалось нельзя фильтровать срезы после пагинации.
        # поэтому сначала фильтруем все объекты а потом делаем срез в зависимости от текущей страницы и шага пагинатора
        if self.kwargs.get('category_id'):
            context['current_category'] = self.kwargs.get('category_id')
            if self.kwargs.get('page_id'):
                context['page_obj'].number = self.kwargs.get('page_id')
            filtered_page_obj = self.object_list.filter(category_id=self.kwargs['category_id']).select_related(
                'category')
            context['page_quantity'] = range(1, len(filtered_page_obj) // self.paginate_by + 2)
            context['page_max'] = len(filtered_page_obj) // self.paginate_by + 1
            # делаем срез в зависимости от текущей страницы и шага пагинатора
            context['page_obj'].object_list = filtered_page_obj[context[
                                                                    'page_obj'].number * self.paginate_by - self.paginate_by:self.paginate_by *
                                                                                                                             context[
                                                                                                                                 'page_obj'].number]
        return context

    def get_price(self, pk):
        return JsonResponse({'price': Product.objects.get(pk=pk).get_product_price()})


class ProductsIndex(ListView):
    model = Product
    title = 'Каталог'
    template_name = 'products/index.html'

class ProductDetailView(ListView):
    model=Product
    title = 'Информация о товаре'
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data()
        context['product'] = ProductsListView.get_product(self.kwargs.get('pk'))
        context['categories'] = ProductCategory.objects.all()
        return context



#
#
#
# def index(request):
#     context = {
#         'title': 'geekshop'
#     }
#     return django.shortcuts.render(request, 'products/index.html', context)


# def products(request, category_id=None, page_id=1):
#     products = Product.objects.filter(category_id=category_id) if category_id != None else Product.objects.all()
#
#     paginator = Paginator(products, per_page=3)
#     try:
#         products_paginator = paginator.page(page_id)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#
#     context = {
#         'img_dir': MEDIA_URL,
#         'title': 'каталог',
#         'categories': ProductCategory.objects.all(),
#         'products': products_paginator
#
#     }
#
#     context.update({'products':products_paginator})
#     return django.shortcuts.render(request, 'products/products.html', context)

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}
        <link href="{% static 'css/index.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'products:index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    {#                <li class="nav-item">#}
                    {#                    <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}#}
                    {#                        <i class="fas fa-user-circle"></i>#}
                    {#                    </a>#}
                    {#                </li>#}
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                {{ user.username|default:'Пользователь' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'users:profile' %}">
                                        профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                        заказы
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admins:index' %}">
                            <i class="fas fa-users-cog"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i
                                class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'js/baskets.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>

</body>

</html>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}


{% block ccs%}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content%}
<!-- Page Content -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:category' category_id='1' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

{% endblock %}

products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все товары</a>
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category }}</a>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-6">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ product.price }} руб</li>
                            <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                        </ul>
                    </div>
                </div>

            </div>

            <div class="col-lg-3">
                {% include 'feedbacks/feedbacks.html' %}
            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все товары</a>
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category }}</a>
                    {% endfor %}

                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in page_obj %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{% url 'products:detail' product.id %}">
                                    <img class="card-img-top"
                                         src={{ product.image.url }}
                                                 alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'products:detail' product.id %}">{{ product.name|capfirst }}</a>
                                    </h4>
                                    <h5>{{ product.price }}</h5>
                                    <p class="card-text">{{ product.description|truncatechars:30 }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'baskets:basket' product.id %}" class="btn btn-outline-success">Отправить
                                        в
                                        корзину</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if not is_categorised %}
                            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_previous %} {% url 'products:page' page_obj.previous_page_number %} {% else %} # {% endif %}"
                                   tabindex="-1" aria-disabled="true">Previous</a>
                            </li>

                            {% for page in page_quantity %}
                                <li class="page-item"><a class="page-link" href="{% url 'products:page' page %}">{{ page }}</a></li>
                            {% endfor %}

                            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_next %} {% url 'products:page' page_obj.next_page_number %} {% else %} # {% endif %}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_previous %} {% url 'products:category_page' current_category page_obj.previous_page_number %} {% else %} # {% endif %}"
                                   tabindex="-1" aria-disabled="true">Previous</a>
                            </li>

                            {% for page in page_quantity %}
                                <li class="page-item"><a class="page-link"
                                                         href="{% url 'products:category_page' current_category page %}">{{ page }}</a>
                                </li>
                            {% endfor %}

                            <li class="page-item {% if page_obj.number == page_max %}disabled{% endif %}">
                                <a class="page-link"
                                   href="{% if  not page_obj.number == page_max %} {% url 'products:category_page' current_category page_obj.next_page_number %} {% else %} # {% endif %}">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}